import assert from "node:assert/strict";
import test from "node:test";
import {
  mergeQuartoFormats,
  parseQuartoInspectionFormats,
  quartoCompletionDocumentation,
  quartoFormatApplies,
  quartoFormatNames,
  quartoFrontMatterFormatContext,
} from "../../src/Notebook/quartoFormats";

test("uses the matching installed Quarto schema description", () => {
  const schemas = {
    "quarto-resource-document-render-keep-md": {
      type: "boolean",
      documentation: "Keep the markdown file generated by executing code",
      tags: {
        description: "Keep the markdown file generated by executing code",
      },
    },
    "quarto-resource-document-toc-toc": {
      type: "boolean",
      documentation: "Include a table of contents",
      tags: {
        description: {
          short: "Include a table of contents",
          long: "Include an automatically generated table of contents.",
        },
      },
    },
  };
  assert.equal(
    quartoCompletionDocumentation(
      {
        type: "key",
        value: "keep-md: ",
        description: "Incorrect neighbouring option description",
        schema: {
          properties: {
            "keep-md": {
              $ref: "quarto-resource-document-render-keep-md",
            },
          },
        },
      },
      schemas
    ),
    "Keep the markdown file generated by executing code"
  );
  assert.equal(
    quartoCompletionDocumentation(
      {
        type: "value",
        value: "true",
        schema: {
          $id: "quarto-resource-document-toc-toc",
          documentation: "Incorrect mutated description",
        },
      },
      schemas
    ),
    "Include an automatically generated table of contents."
  );
});

test("reads live Quarto formats without a built-in format list", () => {
  assert.deepEqual(quartoFormatNames("revealjs"), ["revealjs"]);
  assert.deepEqual(
    quartoFormatNames([{ html: { toc: true } }, "pdf", "html"]),
    ["html", "pdf"]
  );
  assert.deepEqual(
    quartoFrontMatterFormatContext(
      "---\nformat:\n  dashboard:\n    orientation: rows\n  html: default\n---\n"
    ),
    { specified: true, formats: ["dashboard", "html"] }
  );
  assert.deepEqual(
    quartoFrontMatterFormatContext("---\nformat: [html\n---\n"),
    { specified: true, formats: [] }
  );
  assert.deepEqual(
    quartoFrontMatterFormatContext(
      "---\n 'format': [dashboard\n---\n"
    ),
    { specified: true, formats: [] }
  );
  assert.deepEqual(
    quartoFrontMatterFormatContext(
      "---\n \"format\": dashboard\n---\n"
    ),
    { specified: true, formats: ["dashboard"] }
  );
});

test("keeps installed attribute groups for the active document or project format", () => {
  const formats = {
    document: ["revealjs"],
    project: ["html"],
  };
  assert.equal(quartoFormatApplies([], formats), true);
  assert.equal(quartoFormatApplies(["revealjs"], formats), true);
  assert.equal(quartoFormatApplies(["dashboard", "html"], formats), true);
  assert.equal(quartoFormatApplies(["dashboard"], formats), false);
  assert.equal(
    quartoFormatApplies(["dashboard"], {
      document: ["not-dashboard"],
      project: [],
    }),
    false
  );
});

test("uses Quarto's inspected base and active project formats", () => {
  const inspected = parseQuartoInspectionFormats({
    formats: {
      "course-revealjs": {
        identifier: {
          "target-format": "revealjs",
          "base-format": "revealjs",
        },
      },
    },
    project: {
      config: {
        format: {
          "course-revealjs": { theme: "default" },
        },
      },
      extensions: [
        {
          id: { name: "course" },
          contributes: {
            formats: {
              revealjs: { theme: "default" },
            },
          },
        },
      ],
    },
  });
  assert.deepEqual(
    inspected,
    {
      document: ["course-revealjs", "revealjs"],
      project: ["course-revealjs"],
      extensionFormats: {
        "course-revealjs": ["revealjs"],
      },
    }
  );
  assert.deepEqual(
    mergeQuartoFormats(
      { specified: true, formats: ["course-revealjs"] },
      { specified: true, formats: ["course-revealjs"] },
      inspected
    ),
    {
      document: ["course-revealjs", "revealjs"],
      project: ["course-revealjs", "revealjs"],
    }
  );
  assert.deepEqual(
    mergeQuartoFormats(
      { specified: true, formats: ["dashboard"] },
      { specified: true, formats: ["course-revealjs"] },
      inspected
    ),
    {
      document: ["dashboard"],
      project: ["course-revealjs", "revealjs"],
    }
  );
  assert.deepEqual(
    mergeQuartoFormats(
      { specified: true, formats: ["html"] },
      { specified: true, formats: ["html", "revealjs"] },
      {
        document: ["html", "revealjs"],
        project: [],
        extensionFormats: {},
      }
    ),
    {
      document: ["html"],
      project: [],
    }
  );
  assert.deepEqual(
    mergeQuartoFormats(
      { specified: false, formats: [] },
      { specified: false, formats: [] },
      inspected
    ),
    {
      document: ["course-revealjs", "revealjs"],
      project: ["course-revealjs", "revealjs"],
    }
  );
  assert.deepEqual(
    mergeQuartoFormats(
      { specified: true, formats: ["course-revealjs"] },
      { specified: false, formats: [] },
      inspected
    ),
    {
      document: ["course-revealjs", "revealjs"],
      project: ["course-revealjs", "revealjs"],
    }
  );
  assert.deepEqual(
    mergeQuartoFormats(
      { specified: false, formats: [] },
      { specified: true, formats: ["course-revealjs"] },
      inspected
    ),
    {
      document: ["course-revealjs", "revealjs"],
      project: ["course-revealjs", "revealjs"],
    }
  );
  assert.deepEqual(
    mergeQuartoFormats(
      { specified: false, formats: [] },
      { specified: true, formats: ["pdf"] },
      {
        document: ["pdf"],
        project: [],
        extensionFormats: {},
      }
    ),
    {
      document: ["html"],
      project: [],
    }
  );
});
